name: mandi
description: "A new Flutter project."
publish_to: 'none'

version: 0.1.0+20260212

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  appwrite: ^24.0.0
  get_it: ^9.2.1
  go_router: ^17.2.3
  shared_preferences: ^2.5.5
  package_info_plus: ^9.0.1
  gap: ^3.0.1
  multi_listenable: ^0.9.3
  slang: ^4.14.0
  slang_flutter: ^4.14.0
  slang_build_runner: ^4.14.0
  another_flushbar: ^1.12.32
  image: ^4.8.0
  image_picker: ^1.2.2
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.1
  freezed_annotation: ^3.1.0
  dev: ^1.0.0
  json_annotation: ^4.9.0
  openpanel_flutter: ^0.2.0

dev_dependencies:
  freezed: ^3.2.5
  build_runner: ^2.15.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  json_serializable: ^6.13.2

flutter:
  uses-material-design: true
  generate: true

  assets:
  - assets/images/
  - assets/
